version: "3.9"

name: lesson

services:
    app:
        container_name: app
        build:
            context: ./docker/php
            network: host
        ports:
            - "9000:9000"
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www
        working_dir: /var/www
        networks:
            - backend
    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            network: host
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./:/var/www
        networks:
            - backend
    db:
        container_name: db
        build:
            context: ./docker/db
            network: host
        cap_add:
            - SYS_NICE
        networks:
            - backend
        volumes:
            - ./docker/db/db_data:/var/lib/mysql
            - ./docker/db/dumps:/docker-entrypoint-initdb.d/
        ports:
            - '3308:3306'
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PORT=${DB_PORT}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

networks:
    backend:
        name: backend
