version: "3.9"

name: lesson

services:
    app:
        container_name: app
        build:
            context: ./php
            network: host
        ports:
            - "9000:9000"
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www
        working_dir: /var/www
        networks:
            - backend
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./:/var/www
        networks:
            - backend
    db:
        container_name: db
        image: mariadb:latest
        networks:
            - backend
        volumes:
            - ./docker/db/db_data:/var/lib/mysql
            - ./docker/db/dumps:/docker-entrypoint-initdb.d/
        ports:
            - '3308:3306'
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
    backend:
        name: backend
